### ISSUE TITLE
incorrect usage of events

### ISSUE THREAD

**Issue by yuristsepaniuk** [4en1x/NewsPortal#2]
Steps:
1. open FF
2. click on 'raskrit' novost''
**Actual result** --> ReferenceError: event is not defined if (event.target.className === 'tags-input')checkToEnter(event,event.target)
**Expected result** --> News should be expanded.

And this is what I try to locate when I want to understand that you use bubble functionality. Yes, you use it, but make really bad mistake.

Why it works in Chrome? Also it should work in IE. Because when you dispatch event, it is attached to `window` object. This is the reason why your code works in Chrome --> 

**// what is bad**
var eventsInDataContent=()=>{
    // why it works? window.event === event and this is bad!
    // we use closure or ify because we want to get rid of it
    console.log(event);
}

**// what should be done**
var eventsInDataContent=(**event**)=>{
    // now you don't need window.event, right?
    console.log(event);
}

**Comment by 4en1x** [comment]
Just fixed everything.

**Comment by yuristsepaniuk** [comment]
good job! just checked!
