### ISSUE TITLE
good job, really, but some small ideas :)

### ISSUE THREAD

**Issue by yuristsepaniuk** [4en1x/NewsPortal#4]
Dude! We prefer content-type in application/json instead of url-encoded, so normally we expect content-type which you use only in case form submission. If we use xmlhttprequest, then prefer application/json as a body, instead of `xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded')`.

P.S. really good job so far!

**Comment by 4en1x** [comment]
OK ,I changed this place in my code.
