### ISSUE TITLE
code reuse issue

### ISSUE THREAD

**Issue by yuristsepaniuk** [4en1x/NewsPortal#6]
`document.getElementById("link-add-news").style.display = "";`

we have it in lots of places, lets go ahead and create function which accepts element and true|false parameter --> show or hide, for example

function toggle(element, makeVisible) {
     element.style.display = 'you code here to show hide';
}

then use toggle everywhere in your code.

**Comment by 4en1x** [comment]
I close all 3 issue. I redid everything(in general).
