### ISSUE TITLE
code convention 18.12

### ISSUE THREAD

**Issue by yuristsepaniuk** [4en1x/NewsPortal#7]
Hello my friend! What is broken https://github.com/airbnb/javascript#whitespace--max-len

It is much easier for reader to see code in vertical manner, instead of horizontal. So if 100 chars are not enough please use 150, but not more. Anyway better use many lines instead of one very long line.

P.S. please don't over react for getting so many issues, it is good thing, we are learning here, thx for understanding. Good luck with this issue and have a nice week end :)

**Comment by 4en1x** [comment]
I think I correct everything. If there are any other problems with my code (except for splitting large scripts into smaller files), please report.
